### ISSUE TITLE
各位避雷SpaceX社工库，@SpaceSGK，司马骗子，收钱不干活还不退，问就是装死  真的6

### ISSUE THREAD

**Issue by hopeatsd** [Rc-W024/SGK-bot#6]
各位看图吧，真的心累
![微信图片_20240710232143](https://github.com/Rc-W024/SGK-bot/assets/174926480/437edb03-8941-4777-a4d8-0e8e9cdaf47a)
![微信图片_20240710232144](https://github.com/Rc-W024/SGK-bot/assets/174926480/2c142623-6eed-49cd-9910-449ad20915c3)
![微信图片_20240710232145](https://github.com/Rc-W024/SGK-bot/assets/174926480/40466eb1-9b2c-4c7c-89de-de72f5a47a53)
![微信图片_20240710232146](https://github.com/Rc-W024/SGK-bot/assets/174926480/bdced933-3d13-46ac-8fcb-5bf59ca06760)
![微信图片_20240710232147](https://github.com/Rc-W024/SGK-bot/assets/174926480/3db41291-5daa-4e83-bee9-6b8b7e0e3e3a)
![微信图片_20240710232148](https://github.com/Rc-W024/SGK-bot/assets/174926480/d77db2d0-faa0-464a-b4c4-d571cfc85b4c)
![微信图片_20240710232149](https://github.com/Rc-W024/SGK-bot/assets/174926480/6e2eafac-2046-462e-b465-38f903c05d38)
![微信图片_20240710232150](https://github.com/Rc-W024/SGK-bot/assets/174926480/9e19f6ee-ae94-4656-9ad7-fc68166a34fe)
![微信图片_202407102321461](https://github.com/Rc-W024/SGK-bot/assets/174926480/cbc57720-2d4b-4c9b-9c5f-d3cb392917b2)
![微信图片_202407102321481](https://github.com/Rc-W024/SGK-bot/assets/174926480/db766ca4-6199-46ac-8839-0410b9e6b260)

**Comment by hopeatsd** [comment]
这是他们的主页截图
![微信图片_20240710232142](https://github.com/Rc-W024/SGK-bot/assets/174926480/84110e33-503d-41bd-bd02-ca9925fd1d1e)
![微信图片_20240710232150](https://github.com/Rc-W024/SGK-bot/assets/174926480/d5bf3227-dba8-43ed-85e1-8c6df4005bab)
![微信图片_202407102321421](https://github.com/Rc-W024/SGK-bot/assets/174926480/5290d52a-4a69-4017-b4c9-fbce2e1b9d22)
![微信图片_202407102321491](https://github.com/Rc-W024/SGK-bot/assets/174926480/fcab2511-fc58-4b4b-a938-d4eefab21fb9)

**Comment by Rc-W024** [comment]
N/A
